apiVersion: v2
name: observability
description: Argo CD GitOps Controller (Namespace Scoped for sen-dev-dev-azr-k8s-sen-w2-001)
type: application

version: 0.1.0
appVersion: "2.9.3"

dependencies:
  - name: argo-cd
    version: 6.7.3
    repository: https://argoproj.github.io/argo-helm
